# Enable the mouse interaction
setw -g mouse on

# Open pane splits to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
