SOURCE?=~/git/hectormrc/dotfiles/.config/
CONFIG?=~/.config/

all:
	ln -s ${SOURCE}/alacritty \
		${SOURCE}/kitty \
		${SOURCE}/nvim \
		${CONFIG}

clean:
	rm -rf ${CONFIG}/alacritty \
		${CONFIG}/kitty \
		${CONFIG}/nvim
