[terminal.shell]
program = "tmux"

[font]
normal = { family = "JetBrainsMonoNLNerdFont", style = "Regular" }
italic = { style = "Italic" }
bold = { style = "ExtraBold" }
bold_italic = { style = "ExtraBoldItalic" }
